TOPDIR ?= ../..
include $(TOPDIR)/.config

$(TANKLEVEL_SUPPORT)_ECMD_SRC += \
	services/heatctl/heatctl_ecmd.c

$(TANKLEVEL_SUPPORT)_SRC += \
	services/heatctl/heatctl.c \

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
